### Create article type  <Admin>
POST http://localhost:8080/articleType/adm
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MTA3MjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTcxMjgsImlzcyI6Ikt1blV6VGVzdCJ9.Mu91I_ALngSycjEgGNVcS_4j9iISrID8q2xDmD4GWrr8O3968yS_996B-tUqyEM8ii6uo0h5uObmaMD1gOnRow

{
  "orderNumber": 5,
  "nameRu": "Murodbek",
  "nameUz": "Murodjon",
  "nameEng": "Murod"
}

### update  article type <Admin>

PUT http://localhost:8080/articleType/adm?id=1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MTA3MjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTcxMjgsImlzcyI6Ikt1blV6VGVzdCJ9.Mu91I_ALngSycjEgGNVcS_4j9iISrID8q2xDmD4GWrr8O3968yS_996B-tUqyEM8ii6uo0h5uObmaMD1gOnRow

{"orderNumber": 2,
"nameUz": "Murodbek",
"nameRu": "Murodbne",
"nameEng": "Murodne"}

### Delete By id <Admin>
DELETE http://localhost:8080/articleType/adm?id=1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MTA3MjgsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY1OTcxMjgsImlzcyI6Ikt1blV6VGVzdCJ9.Mu91I_ALngSycjEgGNVcS_4j9iISrID8q2xDmD4GWrr8O3968yS_996B-tUqyEM8ii6uo0h5uObmaMD1gOnRow

### Get ALl Pagination <Adnin>;
PUT http://localhost:8080/articleType/adm/getall
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDY1MjM1OTUsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDY2MDk5OTUsImlzcyI6Ikt1blV6VGVzdCJ9.rXc_z6olSToymxVbVstAvuSuGdvvU6RITBqaQiDzzXu1xiWzCuE3pLZV0VeJ-ksWJwSgMS709abfowEj0B6Hyw


### Get By Lang <Any>           <AppLanguage<uz,ru,en>>
GET http://localhost:8080/articleType/getByLang?lang=en