### Admin login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "12345"
}

### User User
POST http://localhost:8080/auth/login
Content-Type: application/json

{
"email": "murod@mail2.ru",
"password": "123"
}

### Create profile
POST http://localhost:8080/auth/registration
Content-Type: application/json

{
  "email": "murod@mail2.ru",
  "name": "Murodbek",
  "surname": "Azimov",
  "password": "123"
}