
### <1> create new category
POST http://localhost:8080/category/adm
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjM0MDcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNDk4MDcsImlzcyI6Ikt1blV6VGVzdCJ9.DhAbIe30bmvESvogcSf9z4kbcPzlzKujGUKE1GMexP2T9ww8LCyG941hPIZ0FhTNbWR9aHjUN1lQb5U9M9nLWw

{"orderNumber": 1,
  "nameEng": "englis",
  "nameUz": "uzbek",
  "nameRu": "Ruschada"
}
### <2> Update by id      <Intejer id>
PUT http://localhost:8080/category/1
Content-Type: application/json
Authorization:  eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjM0MDcsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNDk4MDcsImlzcyI6Ikt1blV6VGVzdCJ9.DhAbIe30bmvESvogcSf9z4kbcPzlzKujGUKE1GMexP2T9ww8LCyG941hPIZ0FhTNbWR9aHjUN1lQb5U9M9nLWw

{"orderNumber": 1,
  "nameEng": "englis",
  "nameUz": "uzbek",
  "nameRu": "Ruschada"
}

### <3> getAll
GET http://localhost:8080/category/getAll
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjY5MjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNTMzMjQsImlzcyI6Ikt1blV6VGVzdCJ9.eFG92LBm-oKqESLxWoCkZeLHcxEV7OMK_k5hOjjIscrUuM4RKDeSgDFHjql2Rm36K6MT44KIxAsUgE0a7li-9A

### <4> get by lang               <AppLanguage<uz,ru,en>>
GET http://localhost:8080/category/getLanguage?lang=ru
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjY5MjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNTMzMjQsImlzcyI6Ikt1blV6VGVzdCJ9.eFG92LBm-oKqESLxWoCkZeLHcxEV7OMK_k5hOjjIscrUuM4RKDeSgDFHjql2Rm36K6MT44KIxAsUgE0a7li-9A

