### <1> create by id
POST http://localhost:8080/region
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNDg4NzEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzMzUyNzEsImlzcyI6Ikt1blV6VGVzdCJ9.Q2vfMdhLCzhxDfe_CZWQ-vvlsiHt7akITVoSk40CwDI-i899DNwQkwf-31UbzDRi-SYJr_eilbJM52u8UCZ8pA

{"nameUz": "uzbek",
  "nameRu": "rus",
  "nameEng": "english",
  "orderNumber": 2
}

### <2> Update by id
PUT http://localhost:8080/region/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNDg4NzEsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzMzUyNzEsImlzcyI6Ikt1blV6VGVzdCJ9.Q2vfMdhLCzhxDfe_CZWQ-vvlsiHt7akITVoSk40CwDI-i899DNwQkwf-31UbzDRi-SYJr_eilbJM52u8UCZ8pA

{"nameUz": "uzbekistan",
  "nameRu": "russian",
  "nameEng": "english",
  "orderNumber": 3
}

### <3> Delete by Id ==Vizible Bolean
DELETE http://localhost:8080/region/1

### <4> Get all list faqat admin jwt kelsa ishga tushadi
GET http://localhost:8080/region/getAllList
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjY5MjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNTMzMjQsImlzcyI6Ikt1blV6VGVzdCJ9.eFG92LBm-oKqESLxWoCkZeLHcxEV7OMK_k5hOjjIscrUuM4RKDeSgDFHjql2Rm36K6MT44KIxAsUgE0a7li-9A


### <5> get By lang
GET http://localhost:8080/region/byLang?lang=uz
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MDYyNjY5MjQsImlkIjoxLCJyb2xlIjoiQURNSU4iLCJleHAiOjE3MDYzNTMzMjQsImlzcyI6Ikt1blV6VGVzdCJ9.eFG92LBm-oKqESLxWoCkZeLHcxEV7OMK_k5hOjjIscrUuM4RKDeSgDFHjql2Rm36K6MT44KIxAsUgE0a7li-9A

